name: dynamo
version: 0.1.0
description: JSON serialization for object graphs
author: Gerald Leeb <gerald@g-24.net>
homepage: https://github.com/gerald24/dynamo
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  logging: ">=0.11.3+1 <0.12.0"
dev_dependencies:
  source_gen: ">=0.5.3"
  build: '>=0.2.1 <0.7.0'
  build_runner: ^0.1.0
  build_test: ^0.3.0
  test: any